language: scala
scala:
  - 2.11.7

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - one@example.com
    on_success: change  # default: change
    on_failure: always # default: always
