FORMAT: 1A

# TravisCI-HelloScalaPlay

Basic API that outputs "Hello World" and inserts simple MongoDB object to database.

# Group Post Collection

End points related to posting to MongoDB.

## Posts [/posts]

### Insert Post to MongoDB [POST]

+ Request (application/json)
    + Attributes (PostRequest)

+ Response 201
    + Attributes (PostResponse)

+ Response 501
    + Attributes (ErrorResponse)

# Data Structures

## homeResponse
+ hello world

## PostRequest (object)
     + Body

            {
                "title": "Hello"
                "body": "World"
            }
     + Schema
            {
                "$schema": "http://json-sche,a.org/draft-04/schema#",
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string"
                    },
                    "body": {
                        "type": "string"
                    }
                }
            }

## PostResponse (object)
+ id: 56c63cd51300002f006649bb (string) - id of the post
+ title: Hello (string, required) - title of post
+ body: World (string, required) - body of post

## ErrorResponse (object)
+ code: 1 (number,required) - The external error code mappable to a UI message and translation.
+ message: 'Something wicked this way comes.' (string,required) - Internal facing error message.